/**
 * Pull request generation.
 *
 * The honest scope, decided the same way 1.1 decided never to fabricate a line
 * number: this extension has no access to a codebase's build tooling, no way
 * to know which of possibly many files a given DOM node came from, and no
 * reliable way to confirm a text replacement in an arbitrary source file
 * wouldn't break something the browser can't see (a template, a generated
 * file, a string used in three other places). Blindly rewriting a file it
 * cannot verify would be reckless, and claiming certainty it doesn't have
 * would repeat exactly the mistake the rest of this product exists to avoid.
 *
 * So this creates a REAL pull request — a real branch, a real commit, a real
 * PR against the repo the user connects — but it carries the same content
 * `fix-export.js` already produces (before/after, selector, WCAG citation,
 * confidence) as a reviewable document, not a blind patch to source the tool
 * has never seen. A developer merges it or acts on it; nothing is silently
 * rewritten in their codebase.
 */

const API = 'https://api.github.com';

function authHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28'
  };
}

async function gh(path, token, opts = {}) {
  const r = await fetch(`${API}${path}`, { ...opts, headers: { ...authHeaders(token), ...(opts.headers || {}) } });
  if (!r.ok) {
    const body = await r.text().catch(() => '');
    throw new Error(`GitHub ${r.status}: ${body.slice(0, 300)}`);
  }
  return r.status === 204 ? null : r.json();
}

/** A short, url-safe branch name — one per scan session, not one per fix. */
function buildBranchName(prefix = 'sitescope360/accessibility-fixes') {
  return `${prefix}-${new Date().toISOString().slice(0, 10)}-${Math.random().toString(36).slice(2, 7)}`;
}

/** Pure — the PR title and body, buildable and testable with no network. */
function buildPrSummary(entries, pageUrl) {
  const list = (entries || []).filter(e => e && e.fix);
  const verified = list.filter(e => e.verified).length;

  const title = `Accessibility fixes${pageUrl ? ` — ${new URL(pageUrl).hostname}` : ''} (${list.length} issue${list.length === 1 ? '' : 's'})`;

  const body = [
    `Generated by SiteScope 360.${pageUrl ? ` Scanned page: ${pageUrl}` : ''}`,
    '',
    `${list.length} fix${list.length === 1 ? '' : 'es'} attached, ${verified} re-scanned and confirmed to clear the violation.`,
    '',
    'This PR documents each fix for review — it does not rewrite files in this repository automatically.',
    'The tool has no way to know which source file a rendered DOM element came from, so applying these',
    'safely is left to a human who can see the actual codebase.',
    '',
    '| Rule | WCAG | Confidence | Verified |',
    '|---|---|---|---|',
    ...list.map(e => `| ${e.issue?.ruleId || e.issue?.id || '—'} | ${(e.issue?.wcag || []).join(', ') || '—'} | ${typeof e.fix.confidence === 'number' ? Math.round(e.fix.confidence * 100) + '%' : '—'} | ${e.verified ? 'Yes' : 'No'} |`),
    '',
    'Full before/after code for each fix is in the attached patch file.'
  ].join('\n');

  return { title, body };
}

/**
 * Create the branch, commit the patch document, and open the PR.
 * `patchContent` is whatever `FixExport.buildSessionExport` already produced —
 * this module does not regenerate it, only ships it.
 */
async function createAccessibilityPr({ token, owner, repo, baseBranch, entries, pageUrl, patchContent }) {
  if (!token || !owner || !repo) throw new Error('GitHub token, owner and repo are required');

  const base = await gh(`/repos/${owner}/${repo}/git/ref/heads/${baseBranch || 'main'}`, token);
  const baseSha = base.object.sha;

  const branch = buildBranchName();
  await gh(`/repos/${owner}/${repo}/git/refs`, token, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha })
  });

  const filePath = `sitescope360/accessibility-fixes-${new Date().toISOString().slice(0, 10)}.patch.txt`;
  await gh(`/repos/${owner}/${repo}/contents/${filePath}`, token, {
    method: 'PUT',
    body: JSON.stringify({
      message: 'Add accessibility fixes from SiteScope 360',
      content: btoa(unescape(encodeURIComponent(patchContent))),
      branch
    })
  });

  const { title, body } = buildPrSummary(entries, pageUrl);
  const pr = await gh(`/repos/${owner}/${repo}/pulls`, token, {
    method: 'POST',
    body: JSON.stringify({ title, body, head: branch, base: baseBranch || 'main' })
  });

  return { url: pr.html_url, branch, number: pr.number };
}

export { buildBranchName, buildPrSummary, createAccessibilityPr };
